const incidents = [
  { year: 1950, event: "Korean War began, impacting millions of lives." },
  { year: 1951, event: "First color television broadcasts started." },
  { year: 1952, event: "Polio vaccine successfully tested." },
  { year: 1953, event: "DNA double helix structure discovered." },
  { year: 1954, event: "First successful kidney transplant." },
  { year: 1955, event: "Rosa Parks sparked the civil rights movement." },
  { year: 1956, event: "Artificial intelligence term was coined." },
  { year: 1957, event: "First satellite Sputnik launched." },
  { year: 1958, event: "NASA was established." },
  { year: 1959, event: "First successful human pacemaker implant." },

  { year: 1960, event: "Laser technology was invented." },
  { year: 1961, event: "First human went to space." },
  { year: 1962, event: "Cuban Missile Crisis nearly caused nuclear war." },
  { year: 1963, event: "Martin Luther King Jr. gave 'I Have a Dream' speech." },
  { year: 1964, event: "Civil Rights Act passed in the US." },
  { year: 1965, event: "First spacewalk performed." },
  { year: 1966, event: "First successful heart transplant." },
  { year: 1967, event: "World’s first ATM installed." },
  { year: 1968, event: "Apollo program advanced moon missions." },
  { year: 1969, event: "Humans landed on the Moon." },

  { year: 1970, event: "First Earth Day raised environmental awareness." },
  { year: 1971, event: "Email was invented." },
  { year: 1972, event: "First CT scan performed." },
  { year: 1973, event: "Mobile phone call made for the first time." },
  { year: 1974, event: "Barcodes used commercially." },
  { year: 1975, event: "Microsoft was founded." },
  { year: 1976, event: "Apple Computer was founded." },
  { year: 1977, event: "First MRI scanner developed." },
  { year: 1978, event: "First test-tube baby born." },
  { year: 1979, event: "Smallpox declared eradicated." },

  { year: 1980, event: "Personal computers entered homes." },
  { year: 1981, event: "First reusable space shuttle launched." },
  { year: 1982, event: "CDs introduced." },
  { year: 1983, event: "Internet TCP/IP standard adopted." },
  { year: 1984, event: "First successful IVF baby in many countries." },
  { year: 1985, event: "DNA fingerprinting introduced." },
  { year: 1986, event: "Chernobyl nuclear disaster." },
  { year: 1987, event: "First smartphone concept introduced." },
  { year: 1988, event: "Global polio eradication initiative launched." },
  { year: 1989, event: "World Wide Web invented." },

  { year: 1990, event: "Human Genome Project began." },
  { year: 1991, event: "First website went live." },
  { year: 1992, event: "SMS text messaging introduced." },
  { year: 1993, event: "GPS became available for civilian use." },
  { year: 1994, event: "Online shopping began." },
  { year: 1995, event: "Internet became publicly accessible." },
  { year: 1996, event: "Cloning of Dolly the sheep." },
  { year: 1997, event: "Deep Blue defeated chess champion." },
  { year: 1998, event: "Google was founded." },
  { year: 1999, event: "Y2K fear highlighted tech dependence." },

  { year: 2000, event: "Human genome draft completed." },
  { year: 2001, event: "9/11 attacks changed global security." },
  { year: 2002, event: "International Space Station expanded." },
  { year: 2003, event: "Human Genome Project completed." },
  { year: 2004, event: "Facebook was launched." },
  { year: 2005, event: "YouTube changed content creation." },
  { year: 2006, event: "Twitter reshaped communication." },
  { year: 2007, event: "iPhone revolutionized smartphones." },
  { year: 2008, event: "Global financial crisis." },
  { year: 2009, event: "Bitcoin introduced decentralized currency." },

  { year: 2010, event: "Social media reshaped activism." },
  { year: 2011, event: "Arab Spring uprisings." },
  { year: 2012, event: "CRISPR gene editing discovered." },
  { year: 2013, event: "3D printing in medicine." },
  { year: 2014, event: "AI began entering daily life." },
  { year: 2015, event: "Paris Climate Agreement signed." },
  { year: 2016, event: "AI defeated world Go champion." },
  { year: 2017, event: "Global movements for equality surged." },
  { year: 2018, event: "Data privacy became a global issue." },
  { year: 2019, event: "Climate strikes led by youth." },

  { year: 2020, event: "COVID-19 pandemic changed human life." },
  { year: 2021, event: "Vaccines developed at record speed." },
  { year: 2022, event: "AI-generated content went mainstream." },
  { year: 2023, event: "Global focus on mental health." },
  { year: 2024, event: "AI became part of everyday work." }
];